server:
  port: 10010

spring:
  application:
    name: gateway

  cloud:
    nacos:
      server-addr: localhost:8848

    gateway:
      routes:
        - id: adminService
          uri: lb://adminService
          predicates:
            - Path=/admin/**


        - id: businessService
          uri: lb://businessService
          predicates:
            - Path=/business/**


        - id: userService
          uri: lb://userService
          predicates:
            - Path=/user/**


      default-filters: #默认过滤器，对所有路由生效


      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期

