server:
  port: 8082

spring:
  application:
    name: adminService

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/admin?useSSL=false&characterEncoding=UTF-8
    username: root
    password: root


  cloud:
    nacos:
      server-addr: nacos:8848

mybatis:
  type-aliases-package: cn.itcast.admin.pojo
  configuration:
    map-underscore-to-camel-case: true
